<?php

declare(strict_types=1);

namespace Masilia\ConsentBundle\Controller\Admin;

use Ibexa\Contracts\AdminUi\Notification\NotificationHandlerInterface;
use Masilia\ConsentBundle\Entity\CookieCategory;
use Masilia\ConsentBundle\Entity\CookiePolicy;
use Masilia\ConsentBundle\Form\Type\CategoryType;
use Masilia\ConsentBundle\Repository\CookieCategoryRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/consent/category', name: 'masilia_consent_admin_category_')]
class CategoryAdminController extends AbstractController
{
    public function __construct(
        private readonly CookieCategoryRepository $categoryRepository,
        private readonly NotificationHandlerInterface $notificationHandler
    ) {
    }

    #[Route('/policy/{policyId}', name: 'list', requirements: ['policyId' => '\d+'], methods: ['GET'])]
    #[ParamConverter('policy', options: ['id' => 'policyId'])]
    public function list(CookiePolicy $policy): Response
    {
        $categories = $this->categoryRepository->findByPolicy($policy);

        return $this->render('@MasiliaConsent/admin/category/list.html.twig', [
            'policy' => $policy,
            'categories' => $categories,
        ]);
    }

    #[Route('/{id}', name: 'view', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function view(CookieCategory $category): Response
    {
        return $this->render('@MasiliaConsent/admin/category/view.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/policy/{policyId}/create', name: 'create', methods: ['POST'], requirements: ['policyId' => '\d+'])]
    #[ParamConverter('policy', options: ['id' => 'policyId'])]
    public function create(Request $request, CookiePolicy $policy): Response
    {
        $category = new CookieCategory();
        $category->setPolicy($policy);
        
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->categoryRepository->save($category, true);
            $this->notificationHandler->success(sprintf('Category "%s" has been created.', $category->getName()));
        } else {
            foreach ($form->getErrors(true) as $error) {
                $this->notificationHandler->error($error->getMessage());
            }
        }

        return $this->redirectToRoute('masilia_consent_admin_policy_view', ['id' => $policy->getId()]);
    }

    #[Route('/{id}/edit', name: 'edit', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function edit(Request $request, CookieCategory $category): Response
    {
        // Prevent editing auto-generated categories
        if ($category->isAutoGenerated()) {
            $this->notificationHandler->error('Cannot edit auto-generated categories from third-party services.');
            return $this->redirectToRoute('masilia_consent_admin_policy_view', ['id' => $category->getPolicy()->getId()]);
        }

        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->categoryRepository->save($category, true);
            $this->notificationHandler->success(sprintf('Category "%s" has been updated.', $category->getName()));
        } else {
            foreach ($form->getErrors(true) as $error) {
                $this->notificationHandler->error($error->getMessage());
            }
        }

        return $this->redirectToRoute('masilia_consent_admin_policy_view', ['id' => $category->getPolicy()->getId()]);
    }

    #[Route('/{id}/delete', name: 'delete', methods: ['POST'], requirements: ['id' => '\d+'])]
    public function delete(Request $request, CookieCategory $category): Response
    {
        $policyId = $category->getPolicy()->getId();

        // Prevent deleting auto-generated categories
        if ($category->isAutoGenerated()) {
            $this->notificationHandler->error('Cannot delete auto-generated categories from third-party services.');
            return $this->redirectToRoute('masilia_consent_admin_policy_view', ['id' => $policyId]);
        }

        if ($this->isCsrfTokenValid('delete' . $category->getId(), $request->request->get('_token'))) {
            $name = $category->getName();
            $this->categoryRepository->remove($category, true);
            $this->notificationHandler->success(sprintf('Category "%s" has been deleted.', $name));
        }

        return $this->redirectToRoute('masilia_consent_admin_policy_view', ['id' => $policyId]);
    }
}
