<?php

declare(strict_types=1);

namespace Masilia\ConsentBundle\Controller\Admin;

use Ibexa\Contracts\AdminUi\Notification\TranslatableNotificationHandlerInterface;
use JMS\TranslationBundle\Annotation\Desc;
use Masilia\ConsentBundle\Entity\Cookie;
use Masilia\ConsentBundle\Entity\CookieCategory;
use Masilia\ConsentBundle\Form\Type\CookieType;
use Masilia\ConsentBundle\Repository\CookieRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/consent/cookie', name: 'masilia_consent_admin_cookie_')]
class CookieAdminController extends AbstractController
{
    public function __construct(
        private readonly CookieRepository $cookieRepository,
        private readonly TranslatableNotificationHandlerInterface $notificationHandler
    ) {
    }

    #[Route('/category/{categoryId}/create', name: 'create', requirements: ['categoryId' => '\d+'], methods: ['GET', 'POST'])]
    #[ParamConverter('category', options: ['id' => 'categoryId'])]
    public function create(Request $request, CookieCategory $category): Response
    {
        $cookie = new Cookie();
        $cookie->setCategory($category);
        
        $form = $this->createForm(CookieType::class, $cookie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->cookieRepository->save($cookie, true);
            $this->notificationHandler->success(
                /** @Desc("Cookie '%name%' has been created.") */
                'cookie.create.success',
                ['%name%' => $cookie->getName()],
                'masilia_consent'
            );
            
            return $this->redirectToRoute('masilia_consent_admin_policy_view', [
                'id' => $category->getPolicy()->getId()
            ]);
        }

        return $this->render('@MasiliaConsent/admin/cookie/create.html.twig', [
            'form' => $form->createView(),
            'category' => $category,
        ]);
    }

    #[Route('/{id}/edit', name: 'edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function edit(Request $request, Cookie $cookie): Response
    {
        // Prevent editing auto-generated cookies
        if ($cookie->isAutoGenerated()) {
            $this->notificationHandler->error(
                /** @Desc("Cannot edit auto-generated cookies from third-party services.") */
                'cookie.edit.error.auto_generated',
                [],
                'masilia_consent'
            );
            return $this->redirectToRoute('masilia_consent_admin_policy_view', [
                'id' => $cookie->getCategory()->getPolicy()->getId()
            ]);
        }

        $form = $this->createForm(CookieType::class, $cookie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->cookieRepository->save($cookie, true);
            $this->notificationHandler->success(
                /** @Desc("Cookie '%name%' has been updated.") */
                'cookie.edit.success',
                ['%name%' => $cookie->getName()],
                'masilia_consent'
            );
            
            return $this->redirectToRoute('masilia_consent_admin_policy_view', [
                'id' => $cookie->getCategory()->getPolicy()->getId()
            ]);
        }

        return $this->render('@MasiliaConsent/admin/cookie/edit.html.twig', [
            'form' => $form->createView(),
            'cookie' => $cookie,
        ]);
    }

    #[Route('/{id}/delete', name: 'delete', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function delete(Request $request, Cookie $cookie): Response
    {
        $policyId = $cookie->getCategory()->getPolicy()->getId();

        // Prevent deleting auto-generated cookies
        if ($cookie->isAutoGenerated()) {
            $this->notificationHandler->error(
                /** @Desc("Cannot delete auto-generated cookies from third-party services.") */
                'cookie.delete.error.auto_generated',
                [],
                'masilia_consent'
            );
            return $this->redirectToRoute('masilia_consent_admin_policy_view', ['id' => $policyId]);
        }

        if ($this->isCsrfTokenValid('delete' . $cookie->getId(), $request->request->get('_token'))) {
            $name = $cookie->getName();
            $this->cookieRepository->remove($cookie, true);
            $this->notificationHandler->success(
                /** @Desc("Cookie '%name%' has been deleted.") */
                'cookie.delete.success',
                ['%name%' => $name],
                'masilia_consent'
            );
        }

        return $this->redirectToRoute('masilia_consent_admin_policy_view', ['id' => $policyId]);
    }
}
